-- Import Lua modules
require('core/options')
require('packer_setup')
require('core/keymaps')
require('core/colors')
require('plugins/neoconf')
require('plugins/nvim-tree')
require('plugins/bufferline')
require('plugins/lsp')
require('plugins/telescope')
require('plugins/treesitter')
require('plugins/alpha')
require('plugins/feline')
