return {
	"stevearc/overseer.nvim",
	opts = {},
	cmd = {
		"OverseerOpen",
		"OverseerClose",
		"OverseerToggle",
		"OverseerSaveBundle",
		"OverseerLoadBundle",
		"OverseerDeleteBundle",
		"OverseerRunCmd",
		"OverseerRun",
		"OverseerInfo",
		"OverseerBuild",
		"OverseerQuickAction",
		"OverseerTaskAction",
		"OverseerClearCache",
	},
	keys = {
		{ "<leader>ot", "<cmd>OverseerToggle<cr>", desc = "Toggle overseer" },
		{ "<leader>oR", "<cmd>OverseerRunCmd<cr>", desc = "Overseer run cmd" },
		{ "<leader>or", "<cmd>OverseerRun<cr>", desc = "Overseer run" },
		{ "<leader>oi", "<cmd>OverseerInfo<cr>", desc = "Overseer info" },
		{ "<leader>ob", "<cmd>OverseerBuild<cr>", desc = "Overseer build" },
	},
}
