return {
	{
		"mrjones2014/smart-splits.nvim",
		config = true,
		keys = {
			{
				"<leader><M-h>",
				function()
					require("smart-splits").resize_left()
				end,
			},
			{
				"<leader><M-j>",
				function()
					require("smart-splits").resize_down()
				end,
			},
			{
				"<leader><M-k>",
				function()
					require("smart-splits").resize_up()
				end,
			},
			{
				"<leader><M-k>",
				function()
					require("smart-splits").resize_right()
				end,
			},
			{
				"<C-h>",
				function()
					require("smart-splits").move_cursor_left()
				end,
			},
			{
				"<C-j>",
				function()
					require("smart-splits").move_cursor_down()
				end,
			},
			{
				"<C-k>",
				function()
					require("smart-splits").move_cursor_up()
				end,
			},
			{
				"<C-l>",
				function()
					require("smart-splits").move_cursor_right()
				end,
			},
			{
				"<leader><C-h>",
				function()
					require("smart-splits").swap_buf_left()
				end,
			},
			{
				"<leader><C-j>",
				function()
					require("smart-splits").swap_buf_down()
				end,
			},
			{
				"<leader><C-k>",
				function()
					require("smart-splits").swap_buf_up()
				end,
			},
			{
				"<leader><C-l>",
				function()
					require("smart-splits").swap_buf_right()
				end,
			},
		},
	},
}
